config/routes.rb
Rails.application.routes.draw do
  root "articles#index"
  
  resources :articles
  get "articles/download_pdf/:id" => "articles#download_pdf", :as => 'download_pdf'

end

app/models/article.rb
class Article < ActiveRecord::Base
    has_one :checksum
    validates :title, presence: true
    validates :body, presence: true, length: {minimum: 10}
end

app/models/checksum.rb
class Checksum < ActiveRecord::Base
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  require 'prawn'
  require 'digest'

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      
      # generates pdf
      file_path = 'articles_pdf/article_' + @article.id.to_s + '.pdf'
      article_pdf = Prawn::Document.new
      article_pdf.text @article.title, style: :bold
      article_pdf.move_down 25
      article_pdf.text @article.body
      article_pdf.move_down 15
      article_pdf.text 'Originally published in ' + @article.created_at.strftime('%d/%m/%Y at %H:%M')
      article_pdf.render_file file_path

      # generates checksums from file and save to database

      md5 = Digest::MD5.file file_path

      sha1 = Digest::SHA1.file file_path

      sha256 = Digest::SHA256.file file_path

      sha512 = Digest::SHA512.file file_path

      @checksum = Checksum.new(md5: md5, sha1: sha1, sha256: sha256, sha512: sha512, article_id: @article.id)
      
      if @checksum.save
        redirect_to @article
      end

    else
      render :new
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to @article
    else
      render :edit
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path
  end

  def download_pdf
    @article = Article.find(params[:id]) 
    file_path = 'articles_pdf/article_' + @article.id.to_s + '.pdf'
    send_file(file_path)
  end

  private
    def article_params
      params.require(:article).permit(:title, :body)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for article do |f| %>
    <div>
        <%= f.label :title %>
        <%= f.text_field :title %>
        <% article.errors.full_messages_for(:title).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>
    <div>
        <%= f.label :body %>
        <%= f.text_area :body %>
        <% article.errors.full_messages_for(:body).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>
    <div>
        <%= f.submit %>
    </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article!</h1>
<%= render "form", article: @article %>
<ul>
    <li><%= link_to "Cancel", article_path(@article) %></li>
</ul>

app/views/articles/index.html.erb
<h1>Articles#index</h1>
<p>Here be a list of articles</p>
<ul>
    <% @articles.each do |article| %>
        <li>
            <%= link_to article.title, article %>
        </li>
    <% end %>
</ul>
<%= link_to "New Article", new_article_path %>

app/views/articles/new.html.erb
<h1>New Article!</h1>
<%= render "form", article: @article %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<p><%= @article.body %></p>
<hr/>
<h2>Checksums</h2>
<ul>
    <li><bold>MD5: </bold><%= @article.checksum.md5 %></li>
    <li><bold>SHA1: </bold><%= @article.checksum.sha1 %></li>
    <li><bold>SHA256: </bold><%= @article.checksum.sha256 %></li>
    <li><bold>SHA512: </bold><%= @article.checksum.sha512 %></li>
</ul>
<hr/>
<ul>
    <li><%= link_to "Download PDF", download_pdf_path(:format => 'pdf') %></li>
    <li><%= link_to "Edit", edit_article_path(@article) %></li>
    <li><%= link_to "Destroy", article_path(@article), method: :delete, data: { confirm: "Are you sure?" } %></li>
    <li><%= link_to "See all articles", articles_path %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>